version: "3.7"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - command
      - query

  command:
    container_name: command-service
    build:
      context: .
      dockerfile: docker/command-service.Dockerfile
    restart: always
    environment:
      POSTGRES_HOST: "103.134.154.18"
      POSTGRES_DB: dot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
      POSTGRES_SSLMODE: require
      REDIS_HOST: "103.134.154.18"
      REDIS_PORT: "6379"
      NATS_ADDRESS: "http://103.134.154.18:31071"
      ELASTICSEARCH_ADDRESS: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "dBSqLPX1mKaUF6ezas8bvjMK"
    ports:
      - 8080
    depends_on:
      - elasticsearch

  query:
    container_name: query-service
    build:
      context: .
      dockerfile: docker/query-service.Dockerfile
    restart: always
    environment:
      POSTGRES_HOST: "103.134.154.18"
      POSTGRES_DB: dot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
      POSTGRES_SSLMODE: require
      REDIS_HOST: "103.134.154.18"
      REDIS_PORT: "6379"
      NATS_ADDRESS: "http://103.134.154.18:31071"
      ELASTICSEARCH_ADDRESS: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "dBSqLPX1mKaUF6ezas8bvjMK"
    ports:
      - 8080
    depends_on:
      - elasticsearch
