version: "3.7"

services:

  # nats:
  #   image: nats-streaming:0.17.0
  #   restart: always

  command:
    container_name: command-service
    build:
      context: .
      dockerfile: docker/command-service.Dockerfile
    restart: always
    environment:
      POSTGRES_HOST: "103.134.154.18"
      POSTGRES_DB: dot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
      POSTGRES_SSLMODE: require
      REDIS_HOST: "103.134.154.18"
      REDIS_PORT: "6379"
      NATS_ADDRESS: "http://103.134.154.18:31071"
      ELASTICSEARCH_ADDRESS: "https://my-deployment-2e0b30.es.asia-southeast1.gcp.elastic-cloud.com"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "dBSqLPX1mKaUF6ezas8bvjMK"
    ports:
      - "8080:8080"

  query:
    container_name: query-service
    build:
      context: .
      dockerfile: docker/query-service.Dockerfile
    restart: always
    environment:
      POSTGRES_HOST: "103.134.154.18"
      POSTGRES_DB: dot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
      POSTGRES_SSLMODE: require
      REDIS_HOST: "103.134.154.18"
      REDIS_PORT: "6379"
      NATS_ADDRESS: "http://103.134.154.18:31071"
      ELASTICSEARCH_ADDRESS: "https://my-deployment-2e0b30.es.asia-southeast1.gcp.elastic-cloud.com"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "dBSqLPX1mKaUF6ezas8bvjMK"
    ports:
      - "8081:8080"
