apiVersion: apps/v1
kind: Deployment                        # Type of Kubernetes resource
metadata:
  name: command-service           # Name of the Kubernetes resource
spec:
  replicas: 1                           # Number of replicas
  selector:
    matchLabels:
      app: command-service        # This deployment applies to any Pods matching the specified label
  template:                             # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                           # The labels that will be applied to all of the pods in this deployment
        app: command-service 
    spec:                               # Spec for the container which will run in the Pod
      containers:
      - name: command-service
        image: command-service:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
